export function getFoodIcon(name: string): string {
  const lower = name.toLowerCase();
  if (lower.includes('chicken')) return '🍗';
  if (lower.includes('beef') || lower.includes('steak') || lower.includes('meat')) return '🥩';
  if (lower.includes('fish') || lower.includes('salmon') || lower.includes('tuna')) return '🐟';
  if (lower.includes('rice')) return '🍚';
  if (lower.includes('pasta') || lower.includes('noodle')) return '🍝';
  if (lower.includes('pizza')) return '🍕';
  if (lower.includes('burger')) return '🍔';
  if (lower.includes('bread') || lower.includes('toast')) return '🍞';
  if (lower.includes('egg')) return '🥚';
  if (lower.includes('milk') || lower.includes('yogurt') || lower.includes('cheese')) return '🥛';
  if (lower.includes('whey') || lower.includes('protein')) return '🥤';
  if (lower.includes('banana')) return '🍌';
  if (lower.includes('apple')) return '🍎';
  if (lower.includes('berry') || lower.includes('strawberry') || lower.includes('blueberry')) return '🍓';
  if (lower.includes('orange')) return '🍊';
  if (lower.includes('grape')) return '🍇';
  if (lower.includes('watermelon')) return '🍉';
  if (lower.includes('avocado')) return '🥑';
  if (lower.includes('broccoli')) return '🥦';
  if (lower.includes('carrot')) return '🥕';
  if (lower.includes('potato') || lower.includes('sweet potato')) return '🍠';
  if (lower.includes('corn')) return '🌽';
  if (lower.includes('salad') || lower.includes('lettuce') || lower.includes('spinach')) return '🥗';
  if (lower.includes('tomato')) return '🍅';
  if (lower.includes('cucumber')) return '🥒';
  if (lower.includes('onion') || lower.includes('garlic')) return '🧅';
  if (lower.includes('mushroom')) return '🍄';
  if (lower.includes('pepper')) return '🫑';
  if (lower.includes('oat') || lower.includes('cereal')) return '🥣';
  if (lower.includes('pancake') || lower.includes('waffle')) return '🥞';
  if (lower.includes('butter') || lower.includes('oil')) return '🧈';
  if (lower.includes('nut') || lower.includes('almond') || lower.includes('peanut')) return '🥜';
  if (lower.includes('chocolate')) return '🍫';
  if (lower.includes('cookie') || lower.includes('biscuit')) return '🍪';
  if (lower.includes('cake') || lower.includes('pastry')) return '🍰';
  if (lower.includes('ice cream')) return '🍦';
  if (lower.includes('candy') || lower.includes('sugar')) return '🍬';
  if (lower.includes('coffee')) return '☕';
  if (lower.includes('tea')) return '🍵';
  if (lower.includes('juice')) return '🧃';
  if (lower.includes('water')) return '💧';
  if (lower.includes('soda') || lower.includes('coke')) return '🥤';
  if (lower.includes('beer')) return '🍺';
  if (lower.includes('wine')) return '🍷';
  return '🍽️';
}
